### ISSUE TITLE
Maybe mention in guide about RAILS_ENV and SECRET_KEY_BASE

### ISSUE THREAD

**Issue by infernalmaster** [nanobox-quickstarts/nanobox-rails#11]
IMHO this can be useful. I followed guide and could not understand why I don't see logs. But then I realized that my production server running Rails in dev mode.
So I added this 2 vars through configuration tab and that solved my issue

**Comment by tsmith-dev** [comment]
This seems to be important information that I'm missing in my setup. My dry-runs and deploys are using the 'development' environment.
